# -*- coding: utf-8 -*-
"""PythonProject2NumberGuesser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VUS7GtVe4Mwglz1dJ4UuH1KwPq7xm9w

Number Guessing game
"""

import random
top_of_range=input("Type a number")
if top_of_range.isdigit():
  top_of_range=int(top_of_range)

  if top_of_range<=0:
    print("please type a larger number than 0 next time")
    quit()

else:
  print("please type a number next time")
  quit()


random_number=random.randint(0,top_of_range)
guesses=0

while True:
  guesses+=1
  user_guess=input("make a guess")
  if user_guess.isdigit():
    user_guess=int(user_guess)
  else:
    print("please type a number next time")
    continue

  if user_guess==random_number:
    print("you got it right")
    break
  elif user_guess> random_number:
    print("you got it wrong! enter a smaller number")
  else:
    print("you got it wrong! enter a larger number")

print("You got it in",guesses,"guesses")


#print(random_number)

